apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: portfolio
  creationTimestamp: null
  labels:
    app: portfolio
  name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portfolio
    spec:
      containers:
      - image: docker.io/ettorefoti/simple-portfolio:latest
        name: simple-portfolio
        resources: {}
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: myregistrykey
status: {}
